const categories = [
    {
        id: 100,
        title: 'Produk Untuk Nasabah',
        level: 1,
        desc: 'Daftar operasional cabang yang dikategorikan berdasarkan tugasnya.',
        sort: 0,
        parent: 0,
        menus: [
            {
                id: 110,
                title: 'Produk Dana',
                level: 2,
                desc: '',
                sort: 0,
                parent: 100,
                menus: [
                    {
                        id: 111,
                        title: 'Deposito',
                        level: 3,
                        desc: '',
                        parent: 110,
                    },
                    {
                        id: 112,
                        title: 'Giro',
                        level: 3,
                        desc: '',
                        parent: 110,
                    },
                    {
                        id: 113,
                        title: 'LAKU',
                        level: 3,
                        desc: '',
                        parent: 110,
                    },
                    {
                        id: 114,
                        title: 'Simpanan Pelajar',
                        level: 3,
                        desc: '',
                        parent: 110,
                    },
                    {
                        id: 115,
                        title: 'TabunganKu',
                        level: 3,
                        desc: '',
                        parent: 110,
                    },
                    {
                        id: 116,
                        title: 'Tahapan Berjangka siMuda',
                        level: 3,
                        desc: '',
                        parent: 110,
                    },
                ]
            },
            {
                id: 120,
                title: 'Produk Investasi & Asuransi',
                level: 2,
                desc: '',
                sort: 1,
                parent: 100,
                menus: [
                    {
                        id: 121,
                        title: 'Bancassurance',
                        level: 3,
                        desc: '',
                        parent: 120,
                    },
                    {
                        id: 122,
                        title: 'DBMM',
                        level: 3,
                        desc: '',
                        parent: 120,
                    },
                    {
                        id: 123,
                        title: 'Reksadana',
                        level: 3,
                        desc: '',
                        parent: 120,
                    },
                    {
                        id: 124,
                        title: 'Obligasi Korporasi',
                        level: 3,
                        desc: '',
                        parent: 120,
                    },
                    {
                        id: 125,
                        title: 'Obligasi Negara',
                        level: 3,
                        desc: '',
                        parent: 120,
                        menus: [
                            {
                                id: 1251,
                                title: 'Obligasi Negara Ritel (ORI)',
                                level: 4,
                                desc: '',
                                parent: 125,
                            },
                            {
                                id: 1252,
                                title: 'Obligasi Negara Valas (INDON)',
                                level: 4,
                                desc: '',
                                parent: 125,
                            },
                            {
                                id: 1253,
                                title: 'Obligasi Negara Valas Syariah (INDOIS)',
                                level: 4,
                                desc: '',
                                parent: 125,
                            },
                        ]
                    },
                    {
                        id: 126,
                        title: 'Sertifikat Berharga BI',
                        level: 3,
                        desc: '',
                        parent: 120,
                        menus: [
                            {
                                id: 1261,
                                title: 'Surat Berharga BI dalam Valas (SBBI Valas)',
                                level: 4,
                                desc: '',
                                parent: 126,
                            },
                            {
                                id: 1262,
                                title: 'Sertifikat Bank Indonesia (SBI)',
                                level: 4,
                                desc: '',
                                parent: 126,
                            },
                        ]
                    }
                ]
            },
            {
                id: 130,
                title: 'Produk Digital',
                level: 2,
                desc: '',
                sort: 2,
                parent: 100,
            },
            {
                id: 140,
                title: 'Produk Kerja sama',
                level: 2,
                desc: '',
                sort: 3,
                parent: 100,
            },
            {
                id: 150,
                title: 'Produk Layanan Perbankan',
                level: 2,
                desc: '',
                sort: 4,
                parent: 100,
            },
            {
                id: 160,
                title: 'Produk Kartu Kredit',
                level: 2,
                desc: '',
                sort: 5,
                parent: 100,
            },
            {
                id: 170,
                title: 'Produk Kredit Konsumtif',
                level: 2,
                desc: '',
                sort: 6,
                parent: 100,
            },
            {
                id: 180,
                title: 'Produk Kredit Produktif',
                level: 2,
                desc: '',
                sort: 7,
                parent: 100,
            },
        ],
        icon: '/menus/coin.svg',
        image: '/struktur/100.svg',
        uri: null,
        edit: true,
    },
    {
        id: 200,
        title: 'Aktivitas Cabang',
        level: 1,
        desc: 'Produk BCA yang digunakan langsung oleh nasabah seperti tabungan e-banking dll.',
        sort: 1,
        parent: 0,
        menus: [
            {
                id: 210,
                title: 'Pengetahuan Perbankan',
                level: 2,
                desc: '',
                sort: 0,
                parent: 200,
            },
            {
                id: 220,
                title: 'Layanan Khusus di Cabang',
                level: 2,
                desc: '',
                sort: 1,
                parent: 200,
            },
            {
                id: 230,
                title: 'Pelaku cabang',
                level: 2,
                desc: '',
                sort: 2,
                parent: 200,
            },
            {
                id: 240,
                title: 'Aktivitas Harian di Cabang',
                level: 2,
                desc: '',
                sort: 3,
                parent: 200,
            },
            {
                id: 250,
                title: 'Pengelolaan nasabah',
                level: 2,
                desc: '',
                sort: 4,
                parent: 200,
            },
        ],
        icon: '/menus/content.svg',
        image: '/struktur/200.svg',
        uri: null,
        edit: true,
    },
    {
        id: 1,
        title: 'Aplikasi Mesin',
        level: 1,
        desc: 'Daftar operasional cabang yang dikategorikan berdasarkan tugasnya.',
        sort: 2,
        parent: 0,
        menus: [
            {
                id: 2,
                title: 'Pendukung Transaksi Umum',
                level: 2,
                desc: '',
                sort: 0,
                parent: 1,
                menus: [
                    {
                        id: 121,
                        title: 'ABACAS',
                        level: 1,
                        desc: '',
                    },
                    {
                        id: 122,
                        title: 'Aplikasi customized report',
                        level: 1,
                        desc: '',
                    }
                ]
            },
            {
                id: 3,
                title: 'Pendukung Transaksi Internasional',
                level: 2,
                desc: '',
                sort: 1,
                parent: 1,
                menus: [
                    {
                        id: 131,
                        title: 'Andy',
                        level: 3,
                        desc: '',
                        parent: 3,
                    },
                    {
                        id: 132,
                        title: 'BDS-OR',
                        level: 3,
                        desc: '',
                        parent: 3,
                    }
                ]
            },
            {
                id: 330,
                title: 'Pendukung Transaksi Kredit',
                level: 2,
                desc: '',
                parent: 1,
                sort: 2,
            },
            {
                id: 340,
                title: 'Internal BCA',
                level: 2,
                desc: '',
                parent: 1,
                sort: 3,
            },
            {
                id: 350,
                title: 'Regulator',
                level: 2,
                desc: '',
                sort: 4,
                parent: 1,
            },
            {
                id: 360,
                title: 'Pendukung Operasional ',
                level: 2,
                desc: '',
                sort: 5,
                parent: 1,
            },
        ],
        icon: '/menus/mypage.svg',
        image: '/struktur/300.svg',
        uri: null,
        edit: true,
    }
];

module.exports = categories;
