server:
  port: 8080
spring:
  profiles: openshift
  rest:
    timeout:
      read: 60000
      connection: 60000
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQL10Dialect
  login:
    max-failed-login: 5
    locking-time-failed-login : 30
  eai:
    ad:
      loginUri: http://dev-bca-pakar-auth-service-d3wiaccred-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/ad-gateways/verify1
      clientId: 8C21EBEEB1AA3FBFE05400144FFBD319
      applicationID: PRJ1
      key: 123456789013245678901234
  security:
    oauth2:
      server:
       url: http://localhost:8080
      clientId: 8C21EBEEB1AA3FBFE05400144FFBD319
      clientSecret: da82edc6dcc1af30
      authorize-grant-type: password,refresh_token
      accessTokenValiditySeconds: 43200
      refreshTokenValiditySeconds: 2592000
    jwt:
      signingkey: pakar123
  dataSource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://36.89.25.220:5432/pakardb3
    username: pakar3
    password: pakar123
    hikari:
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: pakar-oauth-pool
       maximum-pool-size: 20
       max-lifetime: 1800000
       idle-timeout: 30000
       minimum-idle: 5
       connection-timeout: 20000
 